name: Deploy to Live Channel

on:
  push:
    branches: [main]

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run frontend build
        run: |
          cd frontend
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ctrl-mac-simulator
          channelId: live
          entryPoint: frontend
